name: Auto Building Wine Runnerï¼ˆrpmï¼‰
run-name: ${{ github.actor }} Auto Building Wine Runnerï¼ˆrpmï¼‰ ğŸš€
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building RPM
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # é…ç½®ç¯å¢ƒ
          sudo apt update
          sudo apt install git dpkg-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-qmake rpm -y
          git clone https://github.com/gfdgd-xi/deep-wine-runner
          cd deep-wine-runner
          make package-rpm
          mv spark-deepin-wine-runner*.rpm /home/runner/spark-deepin-wine-runner.rpm
      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: spark-deepin-wine-runner.rpm
          path: /home/runner/spark-deepin-wine-runner.rpm
      
    