name: Auto Building Wine Runnerï¼ˆdebï¼‰
run-name: ${{ github.actor }} Auto Building Wine Runnerï¼ˆdebï¼‰ ğŸš€
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building DEB
        run: |
          # é…ç½®ç¯å¢ƒ
          sudo apt update
          sudo apt install git dpkg-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-qmake -y
          git clone https://github.com/gfdgd-xi/deep-wine-runner
          cd deep-wine-runner
          make package-deb
          mv spark-deepin-wine-runner.deb ~
          mv spark-deepin-wine-runner-ace.deb ~
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: spark-deepin-wine-runner.deb
          path: /home/runner/spark-deepin-wine-runner.deb
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: spark-deepin-wine-runner-ace.deb
          path: /home/runner/spark-deepin-wine-runner-ace.deb
      - name: Building DEB (termux)
        run: |
          cd deep-wine-runner
          make package-deb-termux -j4
          mv spark-deepin-wine-runner-termux.deb ~
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: spark-deepin-wine-runner-termux.deb
          path: /home/runner/spark-deepin-wine-runner-termux.deb

    